"""Server-side transparent HTTP forwarder (CP7).

Forwards inbound requests to ``api.anthropic.com`` carrying the
Anthropic credential header (``x-api-key`` / ``anthropic-api-key``)
through unchanged. The llm-tracker bearer (``Authorization``) is
consumed by ``AuthMiddleware`` upstream and is **never** forwarded --
Anthropic would either reject it or, worse, log it.

CP8 will replace this thin shim with the full proxy port (plugin host,
SSE Tee, hook lifecycle, block-response synthesis). CP7's only job is
the credential passthrough surface plus a structured ``proxy.forward``
log entry whose payload the scrubber in ``credential`` keeps clean.
"""

from __future__ import annotations

from collections.abc import AsyncGenerator

import httpx
import structlog
from fastapi.responses import StreamingResponse
from starlette.requests import Request

from .credential import is_credential_header

UPSTREAM_BASE = "https://api.anthropic.com"

# Headers that must be regenerated by httpx for the outbound connection
# or that are meaningless to forward (`Host` would target this server,
# not Anthropic; `Content-Length` is recomputed; `Transfer-Encoding` /
# `Connection` / `Accept-Encoding` are hop-by-hop).
_HOP_BY_HOP: frozenset[str] = frozenset(
    {
        "host",
        "content-length",
        "transfer-encoding",
        "connection",
        "accept-encoding",
    }
)

# Headers the server consumes locally and must NOT pass through. The
# llm-tracker bearer is the only one today; CP8/CP9 may add more (e.g.
# a future `X-LLMTracker-*` family).
_LOCAL_ONLY: frozenset[str] = frozenset({"authorization"})

# Response headers httpx will regenerate or that would confuse a
# streaming client if forwarded verbatim.
_RESPONSE_HOP_BY_HOP: frozenset[str] = frozenset(
    {"transfer-encoding", "connection", "content-encoding"}
)

log = structlog.get_logger(__name__)


def _outbound_headers(headers: httpx.Headers | dict[str, str]) -> dict[str, str]:
    """Filter inbound headers down to what should reach Anthropic."""
    out: dict[str, str] = {}
    for key, value in headers.items():
        lower = key.lower()
        if lower in _HOP_BY_HOP or lower in _LOCAL_ONLY:
            continue
        out[key] = value
    return out


async def forward_request(
    request: Request,
    path: str,
    *,
    http_client: httpx.AsyncClient,
    upstream_base: str = UPSTREAM_BASE,
) -> StreamingResponse:
    """Forward a Starlette request to Anthropic, streaming the response back."""
    body = await request.body()
    headers = _outbound_headers(request.headers)

    # The `forwarded_credential` boolean is the audit signal: it tells
    # an operator whether the request carried an Anthropic credential
    # at all, without ever materialising the value. The scrubber in
    # `credential` is the safety net if a future call site goes wrong;
    # this log call is intentionally already clean.
    log.info(
        "proxy.forward",
        method=request.method,
        path=path,
        forwarded_credential=any(is_credential_header(k) for k in headers),
    )

    url = f"{upstream_base.rstrip('/')}/{path.lstrip('/')}"
    if query := request.url.query:
        url = f"{url}?{query}"

    upstream_req = http_client.build_request(request.method, url, headers=headers, content=body)
    upstream = await http_client.send(upstream_req, stream=True)

    async def generate() -> AsyncGenerator[bytes, None]:
        try:
            async for chunk in upstream.aiter_bytes():
                yield chunk
        finally:
            await upstream.aclose()

    response_headers = {
        k: v for k, v in upstream.headers.items() if k.lower() not in _RESPONSE_HOP_BY_HOP
    }

    return StreamingResponse(
        generate(),
        status_code=upstream.status_code,
        headers=response_headers,
        media_type=upstream.headers.get("content-type"),
    )
